artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://drive.google.com/file/d/1xXVU2sVIPztnqqRG5Dl-Ew9GI-ffSdro/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion/data

base_model:
  root_dir: artifacts/base_model
  base_model_path: artifacts/base_model/base_model.keras
  updated_base_model_path: artifacts/base_model/base_model_updated.keras

training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.keras  
